# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NestVC_Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NestVC_Demo
#pod 'Masonry'
## 下拉刷新
#pod 'MJRefresh', '~>2.0'
#pod 'pop','~>1.0'
pod 'NestVC', :path => './NestVC'
end
